DROP TABLE IF EXISTS TB_HEROES;

CREATE TABLE TB_HEROES (
    ID INT GENERATE ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    POWER TEXT NOT NULL
)

--- CREATE
INSERT INTO TB_HEROES (NAME, POWER)
VALUES
    ('Flash', 'Speed'),
    ('Aquaman', 'Swim'),
    ('Batman', 'Rich')


---READ
SELECT * FROM TB_HEROES;
SELECT * FROM TB_HEROES WHERE NAME='Flash'

---UPDATE
UPDATE TB_HEROES
SET NOME = 'Goku', POWER='All'
WHERE ID = 1

---DELETE
DELETE FROM TB_HEROES WHERE ID = 2